Add the Enhancement sections in reference doc.
microsoft/spring-cloud-azure pull request #854
Opened 2022-02-21 02:55 UTC by Netyyyy

As title.

2022-02-21 03:01 UTC, Netyyyy commented
@backwind1233 please help review this.

2022-02-21 05:53 UTC, yiliuTo requested changes

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +|*spring.cloud.stream.servicebus.bindings.<binding-name>.consumer*.concurrency
I think to put a deprecated property here is to some extent confusing. We only need introduce all the properties supported in 4.x versions. So could you move this part to the migration guide of [service bus binder properties](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_from_azure_spring_cloud_stream_binder_servicebus_to_spring_cloud_azure_stream_binder_servicebus)? We need a table 18 to show the mapping relationship between the legacy propertis and the current one, which is similar with table 15.

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +| false
The default value should be null.

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +| 1
Why is the default value 1?

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +| SubQueue.NONE
Let's keep the default value format of all Enum properties in consistency, just use the string format. So here we can modify it from "SubQueue.NONE" to "none".

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +| Duration.ofMinutes(5)
we should write the default value of each properties in the way how users will write it for a spring boot configuration file. For Duration type, you can refer to https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion.durations

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +| PEEK_LOCK
let's use the lower case, so change it to "peek_lock"

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +|1
why is it 1

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +|*spring.cloud.stream.servicebus.bindings.<binding-name>.consumer*.enable-auto-complete
This property is now not supported to be configured now, let's remove it

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +The following table illustrates how Spring message headers are mapped to Service Bus message headers and properties. When create a message, developers can specify the header or property of a Service
Could you check if we have had similar content already? if so we can remove it here.

2022-02-21 05:53 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-integration-support.adoc
> +The following table illustrates how Spring message headers are mapped to Service Bus message headers and properties. When create a message, developers can specify the header or property of a Service
same here

2022-02-21 08:54 UTC, yiliuTo requested changes

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                    namespace: ${EVENTHUB_NAMESPACE_01}
here the property should be connection-string
![image](https://user-images.githubusercontent.com/63028776/154920695-d45e6833-1444-4363-b18f-84d036ee1f23.png)

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                        account-name: ${CHECKPOINT_STORAGE_ACCOUNT}
same here

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                        account-name: ${CHECKPOINT_STORAGE_ACCOUNT}
we should add a property of connection-string here.

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                    namespace: ${EVENTHUB_NAMESPACE_02}
same here

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                    namespace: ${SERVICEBUS_NAMESPACE_01}
same here, should be connection-string
![image](https://user-images.githubusercontent.com/63028776/154920872-40602196-5e22-433f-ac7a-f4951bbcd965.png)

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                    namespace: ${SERVICEBUS_NAMESPACE_02}
same here

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +===== Multi Binders Support
Let's change the title as "Multi Binder Support"

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +Step 1. To use multiBinders of EventHubs, we need to configure below properties in application.yml
"multiBinders" should be "multiple binders". And let's add the reminder here like 
```
This sample takes connection string as example. Credentials of service priciple and MSI are also supported, users can set related properties in each binder's environment settings.
```

2022-02-21 08:54 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +===== Multi Binders Support
same here

2022-02-21 09:10 UTC, yiliuTo requested changes

2022-02-21 09:10 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                        container-name: ${CHECKPOINT_CONTAINER}
The value should be ${CHECKPOINT_CONTAINER_01}

2022-02-21 09:10 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +                        container-name: ${CHECKPOINT_CONTAINER}
The value should be ${CHECKPOINT_CONTAINER_02}

2022-02-22 01:19 UTC, yiliuTo requested changes

2022-02-22 01:23 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +This sample takes connection string as example. Credentials of service priciple and MSI are also supported, users can set related properties in each binder's environment settings.
Let's add more detailed introduction here: "Connection to mutiple Event Hubs namespaces is also supported by using multi binders."

2022-02-22 01:23 UTC, yiliuTo commented on docs/src/main/asciidoc/spring-cloud-stream-support.adoc
> +This sample takes connection string as example. Credentials of service priciple and MSI are also supported, users can set related properties in each binder's environment settings.
same here: Connection to mutiple Service Bus namespaces is also supported by using multi binders.

2022-02-22 01:33 UTC, yiliuTo approved these changes

2022-02-22 01:41 UTC, merged