Make sure all features are included in spring-security-support.adoc.
microsoft/spring-cloud-azure pull request #880
Opened 2022-03-22 10:52 UTC by chenrujun

As title.

2022-03-22 10:52 UTC, chenrujun commented
Hi, @saragluna , @yiliuTo .
Please help to review this PR when you have time.

2022-03-25 00:01 UTC, chenrujun commented
Hi, @backwind1233 , @saragluna , @yiliuTo , please help to review this PR when you have time.

2022-03-25 06:00 UTC, saragluna requested changes

2022-03-25 09:31 UTC, chenrujun commented on docs/src/main/asciidoc/spring-security-support.adoc
> +|Yes |Yes |`web_application`,`resource_server`,`resource_server_with_obo`, `web_application_and_resource_server` |`resource_server_with_obo`
I didn't find way to achieve that.

Adding a ` ` after `,` will make the table display much better.

Before:
![image](https://user-images.githubusercontent.com/13167207/160094168-9d3afe7b-be91-4bf6-a424-f42e3d0b3ef2.png)

After:
![image](https://user-images.githubusercontent.com/13167207/160094098-316e0b31-31c3-438b-8bed-c6948f78c23a.png)

2022-03-28 01:41 UTC, saragluna approved these changes
LGTM.

2022-03-28 01:51 UTC, merged