Update authentication due to a thread pool bean added
microsoft/spring-cloud-azure pull request #936
Opened 2022-04-29 02:30 UTC by moarychan

Fixes https://github.com/Azure/azure-sdk-for-java/issues/28525

Add a note for the thread pool bean created by Spring Cloud Azure.

2022-05-05 08:56 UTC, saragluna requested changes

2022-05-05 08:56 UTC, saragluna commented on docs/src/main/asciidoc/authentication.adoc
> +NOTE: As of Spring Cloud Azure AutoConfigure 4.1.0, a `ThreadPoolTaskExecutor` bean named **springCloudAzureCredentialTaskExecutor** will be automatically registered by default, which will manage all
which will manage all threads created by Azure Identity.

2022-05-05 08:56 UTC, saragluna commented on docs/src/main/asciidoc/authentication.adoc
> +NOTE: As of Spring Cloud Azure AutoConfigure 4.1.0, a `ThreadPoolTaskExecutor` bean named **springCloudAzureCredentialTaskExecutor** will be automatically registered by default, which will manage all
**az-identity-**

2022-05-05 08:56 UTC, saragluna commented on docs/src/main/asciidoc/authentication.adoc
> +NOTE: As of Spring Cloud Azure AutoConfigure 4.1.0, a `ThreadPoolTaskExecutor` bean named **springCloudAzureCredentialTaskExecutor** will be automatically registered by default, which will manage all
Each thread name managed by this thread pool is prefixed with **az-identity-**. This `ThreadPoolTaskExecutor` bean is independent of the `Executor` bean provided by Spring Boot.

2022-05-06 03:19 UTC, saragluna approved these changes

2022-05-06 05:50 UTC, hui1110 approved these changes

2022-05-16 11:39 UTC, hui1110 commented
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3035

2022-05-30 05:33 UTC, chenrujun commented
Closing this PR.
@hui1110 , please update MS docs first, then sync to this repo.

2022-05-30 05:33 UTC, closed without merging